spring:
  datasource:
    url: jdbc:${LINKDB}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token: ${APIKEY}